@rootURL = http://localhost:4000
# @rootURL = https://mealmob-server.onrender.com
@vendorToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjMyMmEzNGQ0OTI1MWNiNjU0MTY3ZCIsImlhdCI6MTc0NTc1MzU1MSwiZXhwIjoxNzQ1ODM5OTUxfQ.iL4VLKJimFdpdfgM6PJOSev9xthdDhydvXpG5pqELT0
@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTgyY2U3OGU5OGVjYWZlNTQzZjg0NSIsImlhdCI6MTc0NTc1MDkyMSwiZXhwIjoxNzQ1ODM3MzIxfQ.wLt0whTBzP2BNn7cB34PO2YiRPteqioFZmzLvGxebfo

###
POST {{rootURL}}/vendor/register
Content-Type: application/json

{
    "vendorName": "Vendor1",
    "vendorEmail": "vendor1@gmail.com",
    "vendorPassword": "123"
}

###
POST {{rootURL}}/vendor/login
Content-Type: application/json

{
    "vendorEmail": "paradise@gmail.com",
    "vendorPassword": "123"
}

###
POST {{rootURL}}/api/add-restaurant
Content-Type: application/json
Authorization: Bearer {{vendorToken}}

{
    "restaurantName": "Paradise Biryani",
    "restaurantImage": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2024/5/9/39a65ace-1068-4823-86bf-887991751e2a_535931.JPG",
    "rating":4.5,
    "offer":1500,
    "area":"Ramannapet",
    "category":"Both",
    "cuisines":["Biryani", "North-Indian"],
    "vendorId": "67b322a34d49251cb654167d"
}

###
GET {{rootURL}}/api/restaurants?sort_by=&search=r&rating=
Authorization: Bearer {{vendorToken}}

###
PUT {{rootURL}}/api/update-restaurant/67b192742041cdc5360afa4a
Content-Type: application/json
Authorization: Bearer {{vendorToken}}

{
    "restaurantName": "restaurant2",
    "restaurantImage": "",
    "rating":4.5,
    "offer":1500,
    "area":"Banglore",
    "category":"Veg",
    "cuisines":["Biryani", "Pizza"],
    "vendorId": "67b18ae0750691dda935740d"
}

###
POST {{rootURL}}/api/add-foodItem
Content-Type: application/json
Authorization: Bearer {{vendorToken}}

{
    "foodName": "Pizza",
    "foodImage": "c:/Users/pranay/Desktop/food items/pizza-image.jpg",
    "price": 250,
    "category": "Non-Veg",
    "description": "This is a sample Pizza",
    "restaurantId": "67a756d91e0fcf955962ade8"
}

###
// food items by restaurant
GET {{rootURL}}/api/restaurantItems/67b1de81284470da5a28a198
Authorization: Bearer {{vendorToken}}

###
DELETE {{rootURL}}/api/delete-foodItem/67b192742041cdc5360afa4a
Authorization: Bearer {{vendorToken}}

//FOR MEALMOB USERS
###
POST {{rootURL}}/signup
Content-Type: application/json

{
    "username": "lalitha",
    "email": "lalitha123@gmail.com",
    "password": "123"
}
###
POST {{rootURL}}/login
Content-Type: application/json

{
    "username": "pranay",
    "password": "123"
}

###
GET {{rootURL}}/api/restaurants?sort_by=&search=r&rating=
Authorization: Bearer {{userToken}}

###
GET {{rootURL}}/api/restaurantItems/67b1de81284470da5a28a198
Authorization: Bearer {{userToken}}

###
GET {{rootURL}}/api/cuisines?cuisine=Pizza
Authorization: Bearer {{userToken}}

###
// filter food items 
GET {{rootURL}}/api/dishes?sort_by=&search=
Authorization: Bearer {{userToken}}

###
// create order
POST {{rootURL}}/api/orders
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
    "items": [
        {
            "foodId": "67b1de81284470da5a28a198",
            "quantity": 1
        }
    ],
    "address": "123 Main St, Anytown, USA",
    "total": 100
}

###
// get all orders by user token
GET {{rootURL}}/api/all-orders
Authorization: Bearer {{userToken}}


###
// get vendor orders by vendor token
GET {{rootURL}}/api/all-orders
Authorization: Bearer {{vendorToken}}

###
// update order status
PUT {{rootURL}}/api/order-status/680e0f1bf660b4979940198f
Content-Type: application/json
Authorization: Bearer {{vendorToken}}

{
    "status": "delivered"
}
